"""sprint_1_domain_refactor

Revision ID: 16cff05b1eef
Revises: None
Create Date: 2026-06-04 19:21:17.135588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cff05b1eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_code', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('inquiry_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('event_category', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('program_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('program_name', sa.String(length=150), nullable=True))
    op.add_column('projects', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('venue', sa.String(length=150), nullable=True))
    op.add_column('projects', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('event_date_start', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('event_date_end', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('quotation_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('quotation_number', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('program_status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('project_status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('mom_notes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('general_notes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('event_source_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('program_owner_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('program_manager_id', sa.UUID(), nullable=True))
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'users', ['program_owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'event_sources', ['event_source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['program_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('projects', 'program_manager_id')
    op.drop_column('projects', 'program_owner_id')
    op.drop_column('projects', 'event_source_id')
    op.drop_column('projects', 'general_notes')
    op.drop_column('projects', 'mom_notes')
    op.drop_column('projects', 'cancel_reason')
    op.drop_column('projects', 'project_status')
    op.drop_column('projects', 'payment_status')
    op.drop_column('projects', 'program_status')
    op.drop_column('projects', 'quotation_number')
    op.drop_column('projects', 'quotation_date')
    op.drop_column('projects', 'event_date_end')
    op.drop_column('projects', 'event_date_start')
    op.drop_column('projects', 'duration')
    op.drop_column('projects', 'venue')
    op.drop_column('projects', 'quantity')
    op.drop_column('projects', 'program_name')
    op.drop_column('projects', 'program_type')
    op.drop_column('projects', 'event_category')
    op.drop_column('projects', 'inquiry_date')
    op.drop_column('projects', 'project_code')
    # ### end Alembic commands ###
