"""sprint_2_workflow_ui_data_quality

Revision ID: 2c1517cced09
Revises: 16cff05b1eef
Create Date: 2026-06-04 19:29:08.408172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1517cced09'
down_revision = '16cff05b1eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('normalized_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_customers_normalized_name'), 'customers', ['normalized_name'], unique=False)
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('project_status_logs', sa.Column('status_type', sa.String(length=50), nullable=True))
    op.add_column('project_status_logs', sa.Column('old_status', sa.String(length=50), nullable=True))
    op.add_column('project_status_logs', sa.Column('new_status', sa.String(length=50), nullable=True))
    op.add_column('project_status_logs', sa.Column('changed_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('project_status_logs', 'from_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project_status_logs', 'to_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project_status_logs', 'changed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'project_status_logs', 'users', ['changed_by_user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('initial_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_initial_code'), 'users', ['initial_code'], unique=True)
    
    # Create project_activity_logs table if not exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'project_activity_logs' not in tables:
        op.create_table('project_activity_logs',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(), nullable=True),
            sa.Column('project_id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=True),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('field_name', sa.String(length=50), nullable=True),
            sa.Column('old_value', sa.Text(), nullable=True),
            sa.Column('new_value', sa.Text(), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_project_activity_logs_id'), 'project_activity_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_activity_logs_id'), table_name='project_activity_logs')
    op.drop_table('project_activity_logs')
    
    op.drop_index(op.f('ix_users_initial_code'), table_name='users')
    op.drop_column('users', 'initial_code')
    op.drop_constraint(None, 'project_status_logs', type_='foreignkey')
    op.alter_column('project_status_logs', 'changed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('project_status_logs', 'to_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('project_status_logs', 'from_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('project_status_logs', 'changed_by_user_id')
    op.drop_column('project_status_logs', 'new_status')
    op.drop_column('project_status_logs', 'old_status')
    op.drop_column('project_status_logs', 'status_type')
    op.drop_column('documents', 'url')
    op.drop_column('documents', 'document_type')
    op.drop_index(op.f('ix_customers_normalized_name'), table_name='customers')
    op.drop_column('customers', 'normalized_name')
    # ### end Alembic commands ###
